### ISSUE TITLE
Main video content is sometimes visible before the preroll ad starts when the player is positioned differently on the page than in our test pages

### ISSUE THREAD

**Issue by vpitts** [prebid/prebid-js-plugin-brightcove#154]
Customer reported "flashing" of the video content before the preroll on their test page.  This behavior is different from when we use the plugin in our test pages found in our repository.  

It appears that this issue is caused in the Plugin Loader by some incorrect positioning of some of the plugin elements.  This issue will be addressed in the plugin loader.

**Comment by ynisman** [comment]
The black cover div was positioned incorrectly. Modified cover div styles to make sure it covers video content area.

**Comment by vpitts** [comment]
We have fixed the issue in the loader.  However, we do not have available resources at this time to fully test the new code.  In the interim, we are making this fix available through an alternative url so that if you need this fix, you can use it.

INSTRUCTIONS
1.	Replace the existing url used to load the plugin within the Brightcove Studio to:  https://acdn.adnxs.com/video/static/plugins/bc/prebid/js/0.7.5/bc_prebid_vast.min.js 
2.	Republish the player so that this change will take effect

Once we have the resources, will complete the QA process and make the updated loader available through its usual url.

**Comment by vpitts** [comment]
Version 0.7.5 of the prebid plugin loader has been released and published to the CDN:  https://acdn.adnxs.com/video/plugins/bc/prebid/bc_prebid_vast.min.js

To take advantage of this update, you need to re-publish your players using the plugin if you are  loading and configuring the plugin in Brightcove Studio.  Use this url to load the plugin in the Studio:  https://acdn.adnxs.com/video/plugins/bc/prebid/bc_prebid_vast.min.js
