### ISSUE TITLE
Customer reported that the prebid plugin was not compatible with version 5.28.1 of the Brightcove Player

### ISSUE THREAD

**Issue by vpitts** [prebid/prebid-js-plugin-brightcove#22]
One of our customers is using version 5.28.1 of the Brightcove Player.  The prebid plugin had been developed and tested against version 6.24.1 of the Brightcove Player.  It turns out that there are some incompatibilities between the plugin and the older version of the Brightcove Player.

**Comment by graphicdeveloper** [comment]
The Brightcove player 5.28.1 uses video-js version 5. The video-js 5 has a different API for plugin registration, getting registered plugins, and creating html elements in the player. We've modified the plugin to be compatible with both versions of the Brightcove API.
