### ISSUE TITLE
The Brightcove plugin ignores page-level bidderSettings

### ISSUE THREAD

**Issue by graphicdeveloper** [prebid/prebid-js-plugin-brightcove#6]
Publishers have the option to designate a page-level bidderSettings object for prebid.js, as documented here: http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings

**Current Behavior:** The Brightcove Prebid plugin currently ignores this page-level bidderSettings.

**Expected:** Page-level bidderSettings should be honored by the Brightcove plugin

**Comment by vpitts** [comment]
This issue was fixed in Brightcove Prebid Plugin Version 0.1.3 which was released on 8/28/2018.

Closing this issue.
