### ISSUE TITLE
The vast tag I got from prebid is not working on google IMA.

### ISSUE THREAD

**Issue by mistynight89** [prebid/prebid-js-plugin-brightcove#69]
Hi. I generated vast tag using example code from your example page like below.

![prebid1](https://user-images.githubusercontent.com/22162797/50661303-a9bcfe80-0f70-11e9-8746-cfd202d9013a.PNG)

The tag I got is below
https://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&output=vast&unviewed_position_start=1&correlator=1546548816841&sz=640x480&url=http%3A%2F%2Fadmaru.com%2Ftest%2Fprebid_out.html&iu=/19968336/prebid_cache_video_adunit&cust_params=hb_format%3Dvideo%26hb_source%3Dclient%26hb_size%3D640x360%26hb_pb%3D5.00%26hb_adid%3D24d7772b9d2275%26hb_bidder%3Dappnexus%26hb_format_appnexus%3Dvideo%26hb_source_appnexus%3Dclient%26hb_size_appnexus%3D640x360%26hb_pb_appnexus%3D5.00%26hb_adid_appnexus%3D24d7772b9d2275%26hb_bidder_appnexus%3Dappnexus%26hb_uuid%3D12865c7c-01fe-4949-af61-a1c77ada1645%26hb_cache_id%3D12865c7c-01fe-4949-af61-a1c77ada1645

Then, I tried to use this vast tag on google IMA player.

 but it shows  the errors.
![prebid2](https://user-images.githubusercontent.com/22162797/50661411-0cae9580-0f71-11e9-8ec6-46bec265e1de.PNG)

However, when I put the vast tag directly in IMA player, it works.
Do you have any idea of it?

**Comment by vpitts** [comment]
So several things to ask you:
- What is the difference between your "google IMA player" where you are seeing the errors and your "IMA player" where it works?

- The vast tag makes a call to the prebid cache - if you look in the contents of what the vast tag returns, you will see the VastTagUri point to "https://prebid.adnxs.com/pbc/v1/cache?uuid=12865c7c-01fe-4949-af61-a1c77ada1645"  This is a cache that prebid uses to store the results of prebid.  That cache is not persistent and if you try to hit it too long after you made the prebid call, that cache may be empty.

- The vast tag also includes other query string parameters that are added by prebid such as hb_pb and hb_adid.  These are parameters that DFP will use to determine which ad to return.  

- If you can give us a link to your test page which includes your options, we can take a look at it to see what might be going wrong.

- What link to the plugin are you using?

- Why do you want to use the IMA player and not the Brightcove Player?

**Comment by mistynight89** [comment]
Hi.
Thank you for reply.

At first IMA players are same one.

http://admaru.com/test/prebid_out.html
In this page, I set the vast tag to global variable, and then I try to use this tag in IMA player.
But it show the errors.

http://admaru.com/test/prebid_out2.html
In this page, I put the vast tag in the IMA player file, and it shows the video.

I don't understand what is different.

**Comment by vpitts** [comment]
Also one thing we did notice is that you are using a different defineSlot on DFP on the 2 pages - maybe this is where the error is

**Comment by vpitts** [comment]
Closing this issue since the question does not seem to be released to the plugin.
