### ISSUE TITLE
No ad will play when prebid.js fails to load even if there are DFP parameters specified

### ISSUE THREAD

**Issue by vpitts** [prebid/prebid-js-plugin-brightcove#83]
Sometimes the plugin is unable to load prebid.js - particularly if timeouts are sent too low.  In that case, it is expected not to have any bids back from prebid since prebid was unable to run.  However, if the customer had also specified targeting parameters for DFP (or other primary ad server), that ad call is also not made and as a result, there is no ad displayed.  It is proposed that the failure of loading prebid should not block making an ad call to primary ad server.  The behavior should be similar to the case when prebid is present but returns back no bids.

**Comment by vpitts** [comment]
The described behavior occurs because the prebid code knows how to make the DFP call.  And, since prebid.js failed to load, the knowledge about how to construct the DFP call is also missing.

**Comment by vpitts** [comment]
The proposed solution involves importing in the code that knows how to construct the DFP call into the plugin.  So, in the event that prebid fails to load, the plugin can go ahead and make the call to DFP to get back an ad.

**Comment by vpitts** [comment]
The fix for this issue also addresses the case where the plugin is configured to send the results of prebid to another ad server other than DFP.

**Comment by ynisman** [comment]
This issue was fixed and released in plugin version 0.4.14
