### ISSUE TITLE
When the player requests a postroll from the plugin, the following error can be thrown:  VIDEOJS: ERROR: TypeError: m.playlist.currentIndex is not a function. This can result in the player freezing.

### ISSUE THREAD

**Issue by vpitts** [prebid/prebid-js-plugin-brightcove#84]
"VIDEOJS: ERROR: TypeError: m.playlist.currentIndex is not a function" has been detected when the prebid plugin has been asked to play a postroll ad.  When this error is thrown, it can cause the player to freeze with a black screen and loading spinner.

**Comment by ynisman** [comment]
Fixed for Plugin version 0.4.11
